# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-23 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('codigo', models.CharField(default='', max_length=1, primary_key=True, serialize=False, verbose_name='Código FIFe')),
                ('nome', models.CharField(default='', max_length=30, verbose_name='Nome')),
                ('descricao', models.CharField(default='', max_length=120, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Cores',
                'verbose_name': 'Cor',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Cor_Complementar',
            fields=[
                ('codigo', models.CharField(default='', max_length=2, primary_key=True, serialize=False, verbose_name='Código FIFe')),
                ('nome', models.CharField(default='', max_length=30, verbose_name='Nome')),
                ('descricao', models.CharField(default='', max_length=120, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Cores Complementares',
                'verbose_name': 'Cor Complementar',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Cor_Olhos',
            fields=[
                ('codigo', models.CharField(default='', max_length=2, primary_key=True, serialize=False, verbose_name='Código FIFe')),
                ('nome', models.CharField(default='', max_length=30, verbose_name='Nome')),
                ('descricao', models.CharField(default='', max_length=120, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Cores dos Olhos',
                'verbose_name': 'Cor dos Olhos',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('ems', models.CharField(default='', max_length=3, primary_key=True, serialize=False, verbose_name='Código EMS')),
                ('nome', models.CharField(default='', max_length=30, verbose_name='Raça')),
                ('descricao', models.CharField(default='', max_length=120, verbose_name='Descrição')),
                ('raca_irma', models.CharField(default='', max_length=30, verbose_name='Raça Irmã')),
                ('categoria', models.CharField(choices=[('1', 'Categoria 1'), ('2', 'Categoria 2'), ('3', 'Categoria 3'), ('4', 'Categoria 4')], default='4', help_text='Categoria da raça', max_length=1, verbose_name='Categoria')),
                ('reconhecida', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', help_text='Se a raça é reconhecida ou não', max_length=1, verbose_name='Raça Reconhecida')),
            ],
            options={
                'verbose_name_plural': 'Raças',
                'verbose_name': 'Raça',
                'ordering': ('nome',),
            },
        ),
    ]
