# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-24 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basico', '0003_regra_raca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raca',
            name='descricao',
            field=models.CharField(default='', max_length=120, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='raca',
            name='raca_irma',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='Raça Irmã'),
        ),
    ]
