# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-24 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basico', '0004_auto_20181224_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regra',
            name='regra',
            field=models.CharField(default='', max_length=30, verbose_name='Regra'),
        ),
        migrations.AlterUniqueTogether(
            name='regra',
            unique_together=set([('raca', 'regra')]),
        ),
    ]
