# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-29 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basico', '0005_auto_20181224_1624'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='regra',
            unique_together=set([('raca', 'regra', 'descricao')]),
        ),
    ]
