# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-29 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basico', '0006_auto_20181229_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raca',
            name='categoria',
            field=models.CharField(choices=[('1', 'Categoria 1'), ('2', 'Categoria 2'), ('3', 'Categoria 3'), ('4', 'Categoria 4')], default='4', help_text='Categoria da raça', max_length=1, null=True, verbose_name='Categoria'),
        ),
    ]
