# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-04 16:26
from __future__ import unicode_literals

import common.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from model_utils.fields import AutoCreatedField, AutoLastModifiedField


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_auto_20180405_1133'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basico', '0008_auto_20181229_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, default='', max_length=255, verbose_name='Descrição')),
                ('documento', models.FileField(upload_to='documentos/')),
                ('created_at', common.fields.AutoCreatedAtField(verbose_name='Data de Criação')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documento_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado Por')),
            ],
            options={
                'verbose_name_plural': 'Documentos',
                'verbose_name': 'Documento',
            },
        ),
        migrations.CreateModel(
            name='Gatil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=30, verbose_name='Nome')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.Pessoa', verbose_name='Proprieeatingtário')),
            ],
            options={
                'verbose_name_plural': 'Cores',
                'ordering': ('nome',),
                'verbose_name': 'Cor',
            },
        ),
        migrations.CreateModel(
            name='Gato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100, verbose_name='Nome')),
                ('sexo', models.CharField(choices=[('F', 'Fêmea'), ('M', 'Macho')], default='F', help_text='Sexo', max_length=1, verbose_name='Sexo')),
                ('status', models.CharField(choices=[('C', 'Em cadastro'), ('P', 'Pendente'), ('H', 'Habilitado'), ('I', 'Inativo')], default='C', help_text='Status', max_length=1, verbose_name='Status')),
                ('created_at', common.fields.AutoCreatedAtField(verbose_name='Data de Criação')),
                ('modified_at', AutoLastModifiedField(verbose_name='Última Modificação')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basico.Regra', verbose_name='Cor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gato_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado Por')),
                ('gatil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basico.Gatil', verbose_name='Gatil')),
                ('mae', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gata_mae', to='basico.Gato', verbose_name='Mãe')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gato_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado Por')),
                ('pai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gato_pai', to='basico.Gato', verbose_name='Pai')),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basico.Raca', verbose_name='Raça')),
            ],
            options={
                'verbose_name_plural': 'Gato',
                'ordering': ('raca', 'cor', 'nome'),
                'verbose_name': 'Gato',
            },
        ),
        migrations.CreateModel(
            name='Gato_Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basico.Documento', verbose_name='Documento')),
                ('gato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basico.Gato', verbose_name='Gato')),
            ],
            options={
                'verbose_name_plural': 'Gato_Documentos',
                'ordering': ('gato', 'documento'),
                'verbose_name': 'Gato_Documento',
            },
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataini', models.DateField(verbose_name='Data Início Propriedade')),
                ('datafin', models.DateField(blank=True, null=True, verbose_name='Data Término Propriedade')),
                ('gato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basico.Gato', verbose_name='Gato')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.Pessoa', verbose_name='Proprietário')),
            ],
            options={
                'verbose_name_plural': 'Proprietários',
                'ordering': ('gato', 'proprietario', 'dataini'),
                'verbose_name': 'Proprietário',
            },
        ),
        migrations.AlterUniqueTogether(
            name='proprietario',
            unique_together=set([('gato', 'proprietario')]),
        ),
        migrations.AlterUniqueTogether(
            name='gato_documento',
            unique_together=set([('gato', 'documento')]),
        ),
    ]
