# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-04 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basico', '0009_auto_20190304_1326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cor',
        ),
        migrations.DeleteModel(
            name='Cor_Complementar',
        ),
        migrations.DeleteModel(
            name='Cor_Olhos',
        ),
        migrations.AlterModelOptions(
            name='gatil',
            options={'ordering': ('nome',), 'verbose_name': 'Gatil', 'verbose_name_plural': 'Gatis'},
        ),
        migrations.AlterField(
            model_name='gatil',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.Pessoa', verbose_name='Proprietário'),
        ),
    ]
