# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-04 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basico', '0010_auto_20190304_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gato',
            name='gatil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basico.Gatil', verbose_name='Gatil'),
        ),
        migrations.AlterField(
            model_name='gato',
            name='mae',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gata_mae', to='basico.Gato', verbose_name='Mãe'),
        ),
        migrations.AlterField(
            model_name='gato',
            name='pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gato_pai', to='basico.Gato', verbose_name='Pai'),
        ),
    ]
