# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-06 17:50
from __future__ import unicode_literals

import common.fields
from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('basico', '0011_auto_20190304_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gato',
            name='modified_at',
            field=common.fields.AutoModifiedAtField(default=django.utils.timezone.now, verbose_name='Última Modificação'),
        ),
        migrations.AlterField(
            model_name='gato',
            name='sexo',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='F', max_length=100, no_check_for_status=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='gato',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='1', max_length=100, no_check_for_status=True),
        ),
    ]
