# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-10 14:08
from __future__ import unicode_literals

import common.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basico', '0015_auto_20190310_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninhada',
            name='created_at',
            field=common.fields.AutoCreatedAtField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='ninhada',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ninhada_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado Por'),
        ),
        migrations.AddField(
            model_name='ninhada',
            name='modified_at',
            field=common.fields.AutoModifiedAtField(default=django.utils.timezone.now, verbose_name='Última Modificação'),
        ),
        migrations.AddField(
            model_name='ninhada',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ninhada_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado Por'),
        ),
    ]
