# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-10 14:28
from __future__ import unicode_literals

import common.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basico', '0016_auto_20190310_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='modified_at',
            field=common.fields.AutoModifiedAtField(default=django.utils.timezone.now, verbose_name='Última Modificação'),
        ),
        migrations.AddField(
            model_name='documento',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documento_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado Por'),
        ),
        migrations.AddField(
            model_name='ninhada',
            name='datanasc',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='ninhada',
            name='gatil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basico.Gatil', verbose_name='Gatil'),
        ),
        migrations.AddField(
            model_name='ninhada',
            name='qtde',
            field=models.IntegerField(null=True, verbose_name='Quantidade de filhotes'),
        ),
        migrations.AddField(
            model_name='ninhada',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='R', max_length=100, no_check_for_status=True, verbose_name='LO/RX'),
        ),
    ]
