# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-10 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basico', '0017_auto_20190310_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='gato',
            name='ninhada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basico.Ninhada', verbose_name='Ninhada'),
        ),
    ]
