# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-10 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basico', '0018_gato_ninhada'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ninhada',
            unique_together=set([('pai', 'mae', 'datanasc')]),
        ),
    ]
