# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-10 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basico', '0019_auto_20190310_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninhada',
            name='outcross',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', help_text='Se o cruzamento é com raças não autorizadas.', max_length=1, verbose_name='Outcross'),
        ),
    ]
