# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-12 21:18
from model_utils.fields import AutoCreatedField, AutoLastModifiedField

import cliente.fields
import cliente.models
import common.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.utils.timezone

import common.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEP',
            fields=[
                ('cep', models.CharField(default='', max_length=9, primary_key=True, serialize=False, verbose_name='CEP')),
                ('endereco', models.CharField(default='', help_text='Logradouro conforme Correios', max_length=60, verbose_name='Endereço')),
                ('bairro', models.CharField(default='', help_text='Bairro conforme Correios', max_length=60)),
            ],
            options={
                'verbose_name_plural': 'CEPs',
                'ordering': ('cep', 'estado'),
                'verbose_name': 'CEP',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('sigla', models.CharField(default='', max_length=2, primary_key=True, serialize=False, verbose_name='Sigla')),
                ('estado', models.CharField(default='', max_length=20, verbose_name='Estado')),
                ('ibge', models.CharField(default='', help_text='Código IBGE do Estado', max_length=2, verbose_name='Código IBGE')),
            ],
            options={
                'verbose_name_plural': 'Estados',
                'ordering': ('sigla', 'estado'),
                'verbose_name': 'Estado',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('ibge', models.CharField(default='', help_text='Código IBGE do Município', max_length=7, primary_key=True, serialize=False, verbose_name='Código IBGE')),
                ('nome', models.CharField(default='', max_length=60, verbose_name='Município')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.Estado', verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'Municípios',
                'ordering': ('uf', 'nome'),
                'verbose_name': 'Município',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=80)),
                ('email', models.EmailField(blank=True, default='', help_text='eMail de contato', max_length=80, null=True, validators=[django.core.validators.EmailValidator(message='Entre um endereço de eMail válido')], verbose_name='Email de Contato')),
                ('emailnf', models.EmailField(blank=True, default='', help_text='eMail de recebimento de NFe', max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Entre um endereço de eMail válido')], verbose_name='Email da NFe')),
                ('msg', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Mensagem')),
                ('telefone', models.CharField(blank=True, default='', help_text='Formato: (99) 9999-9999', max_length=15, null=True)),
                ('celular', models.CharField(blank=True, default='', help_text='Formato: (99) 99999-9999', max_length=15, null=True)),
                ('ativo', models.CharField(blank=True, choices=[('S', 'Ativo'), ('I', 'Inativo')], default='S', max_length=1, null=True, verbose_name='Status')),
                ('usuariointernet', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Usuario Internet')),
                ('senhainternet', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Senha Internet')),
                ('endereco', models.CharField(default='', help_text='Preencha sem abreviações. Ex: Rua Lobo Júnior', max_length=60, verbose_name='Endereço')),
                ('enderecoNumero', models.CharField(default='', help_text="Ou 'S/N' se não existir", max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(default='', help_text='Preencha sem abreviações. Ex: Penha', max_length=60)),
                ('cep', models.CharField(default='', help_text='Ex.: 21020-122', max_length=9, verbose_name='CEP')),
                ('created_at', AutoCreatedField(verbose_name='Data de Criação')),
                ('modified_at', AutoLastModifiedField(verbose_name='Última Modificação')),
                ('tipo', models.CharField(blank=True, choices=[('F', 'Pessoa Física'), ('J', 'Pessoa Jurídica')], default='P', editable=False, max_length=1, null=True, verbose_name='Tipo de Pessoa')),
                ('slug', models.SlugField(default='1', max_length=100, unique=True, validators=[
                    common.utils.validate_pessoa_slug])),
            ],
            options={
                'verbose_name_plural': 'Pessoas',
                'ordering': ('nome',),
                'verbose_name': 'Pessoa',
            },
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cliente.Pessoa')),
                ('cpf', models.CharField(max_length=14, validators=[common.utils.validate_cpf])),
                ('rg', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('orgaoexpedidor', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='Órgão Expedidor')),
                ('dataexp', models.DateField(blank=True, null=True, verbose_name='Data Expedição')),
                ('sexo', models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1, null=True)),
                ('datanascimento', models.DateField(blank=True, null=True, verbose_name='Nascimento')),
                ('estadocivil', models.CharField(blank=True, choices=[('C', 'Casado'), ('S', 'Solteiro'), ('D', 'Divorciado'), ('', 'União Civil')], default='C', max_length=1, null=True, verbose_name='Estado Civil')),
                ('nacionalidade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('naturalidade', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('pai', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('mae', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Mãe')),
                ('passaporte', models.CharField(blank=True, default='', max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pessoas Físicas',
                'verbose_name': 'Pessoa Física',
            },
            bases=('cliente.pessoa',),
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cliente.Pessoa')),
                ('cnpj', models.CharField(max_length=18, validators=[common.utils.validate_cnpj])),
                ('contato', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('nrinscrmunicip', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Inscrição Municipal')),
                ('nrinscrestadual', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Inscrição Estadual')),
            ],
            options={
                'verbose_name_plural': 'Pessoas Jurídicas',
                'verbose_name': 'Pessoa Jurídica',
            },
            bases=('cliente.pessoa',),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pessoa_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado Por'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.Estado'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pessoa_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado Por'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='municipio',
            field=cliente.fields.MunicipioForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.Municipio'),
        ),
        migrations.AddField(
            model_name='cep',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.Estado'),
        ),
        migrations.AddField(
            model_name='cep',
            name='municipio',
            field=cliente.fields.MunicipioForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.Municipio'),
        ),
    ]
