# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-19 14:37


import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finan', '0002_auto_20170212_1918'),
        ('cliente', '0002_auto_20170212_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.PositiveSmallIntegerField(default=0, help_text='Agência bancária sem DV', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Agência')),
                ('agencia_dv', models.CharField(blank=True, default='', help_text='DV da agência bancária', max_length=2, verbose_name='DV Agência')),
                ('conta', models.DecimalField(decimal_places=0, default=0, help_text='Número da conta sem DV', max_digits=13, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999999999999)], verbose_name='Conta')),
                ('conta_dv', models.CharField(blank=True, default='', help_text='DV da conta corrente', max_length=2, verbose_name='DV Conta')),
                ('tipo_conta', models.CharField(blank=True, choices=[('1', 'Corrente'), ('2', 'Poupança'), ('3', 'Investimento'), ('4', 'Outro')], default='1', max_length=1, verbose_name='Tipo de Conta')),
                ('ativo', models.CharField(blank=True, choices=[('S', 'Ativo'), ('I', 'Inativo')], default='S', max_length=1, null=True, verbose_name='Status')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finan.Banco')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.Pessoa')),
            ],
            options={
                'ordering': ('banco', 'agencia'),
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
            },
        ),
    ]
