# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 20:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20180215_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cep',
            name='endereco',
            field=models.CharField(default='', help_text='Logradouro conforme Correios', max_length=60, verbose_name='Endereço'),
        ),
    ]
