# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 23:20


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20180215_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='slug',
            field=models.SlugField(default='1', max_length=100),
        ),
    ]
