# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 14:33


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_auto_20180223_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='slug',
            field=models.SlugField(blank=True, default='1', max_length=100, null=True),
        ),
    ]
