# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-12 21:18


import common.fields
import common.models
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import mptt.fields
from model_utils.fields import AutoCreatedField, AutoLastModifiedField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('codigoCompensacao', models.CharField(default='', max_length=3, primary_key=True, serialize=False, verbose_name='Código Compensação')),
                ('nome', models.CharField(default='', max_length=60, verbose_name='Nome')),
            ],
            options={
                'verbose_name_plural': 'Bancos',
                'ordering': ('nome',),
                'verbose_name': 'Banco',
            },
        ),
        migrations.CreateModel(
            name='ContaContabil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta', models.CharField(default='99', max_length=20, verbose_name='Conta Contábil')),
                ('finalConta', models.CharField(default='99', max_length=3, verbose_name='Final da Conta Contábil')),
                ('nome', models.CharField(default='', max_length=60, verbose_name='Nome')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finan.ContaContabil', verbose_name='Conta Contábil Pai')),
            ],
            options={
                'verbose_name_plural': 'Contas Contábeis',
                'ordering': ('nome',),
                'verbose_name': 'Conta Contábil',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PlanoDeContas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=60, verbose_name='Plano de Contas')),
                ('descricao', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Descrição do Plano de Contas')),
                ('ativo', models.CharField(blank=True, choices=[('S', 'Ativo'), ('I', 'Inativo')], default='S', max_length=1, null=True, verbose_name='Status')),
                ('created_at', AutoCreatedField(verbose_name='Data de Criação')),
                ('modified_at', AutoLastModifiedField(verbose_name='Última Modificação')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planodecontas_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado Por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planodecontas_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado Por')),
            ],
            options={
                'verbose_name_plural': 'Planos de Contas',
                'ordering': ('nome',),
                'verbose_name': 'Plano de Contas',
            },
        ),
        migrations.AddField(
            model_name='contacontabil',
            name='planodecontas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planodecontasfk', to='finan.PlanoDeContas', verbose_name='Plano de Contas'),
        ),
        migrations.AlterUniqueTogether(
            name='contacontabil',
            unique_together=set([('conta', 'planodecontas')]),
        ),
    ]
