# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-01 22:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finan', '0002_auto_20170212_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=60, verbose_name='Nome')),
            ],
            options={
                'ordering': ('nome',),
                'verbose_name': 'Índice de Correção',
                'verbose_name_plural': 'Índices de Correção',
            },
        ),
    ]
