# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 16:32


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finan', '0003_indice'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contacontabil',
            managers=[
            ],
        ),
    ]
