# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-16 19:36


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0007_auto_20180405_1133'),
        ('common', '0002_configuracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('configuracao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Configuracao')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.PessoaJuridica', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuracao',
                'ordering': ('apelido',),
                'verbose_name_plural': 'Configurações',
                'manager_inheritance_from_future': True,
            },
            bases=('common.configuracao',),
        ),
    ]
